### ISSUE TITLE
MacOS: fatal error: argp.h: No such file or directory

### ISSUE THREAD

**Issue by tseemann** [yhg926/public_kssd#2]
```
fatal error: argp.h: No such file or directory
```

this seems to be glibc specific so won't compile on macos

**Comment by yhg926** [comment]
Yes, you are right. Kssd currently can only run on Linux system.

**Comment by tseemann** [comment]
Can you change docs please?

OLD: `Kssd run on linux system.`
NEW: `Kssd runs only on Linux systems. It does not support MacOS.`

Thank you.

**Comment by yhg926** [comment]
Done! Neither for Windows.

**Comment by tseemann** [comment]
There is a package in `brew` called `argp-standalone` and can be used to build on macos.

**Comment by jianshu93** [comment]
I still have the sysinfo.h not found error on MacOS, is this solved? 

Thanks,

Jianshu

**Comment by yhg926** [comment]
> I still have the sysinfo.h not found error on MacOS, is this solved?
> 
> Thanks,
> 
> Jianshu

currently only linux environment is supported.

**Comment by jianshu93** [comment]
thanks！

It would be nice to have a macos version！

Jianshu
